# Generated by Django 5.0 on 2023-12-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car_charging", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chargingsession",
            name="user_full_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="User Full Name"),
        ),
        migrations.AlterField(
            model_name="chargingsession",
            name="user_id",
            field=models.UUIDField(blank=True, null=True, verbose_name="User ID"),
        ),
    ]
