# Generated by Django 5.0 on 2023-12-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car_charging", "0002_alter_chargingsession_user_full_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZaptecToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.TextField(verbose_name="Token")),
                ("token_type", models.CharField(blank=True, max_length=100, verbose_name="Token Type")),
                ("expires_in", models.IntegerField(blank=True, null=True, verbose_name="Time to expire [s]")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
            ],
            options={
                "verbose_name": "Zaptec Token",
                "verbose_name_plural": "Zaptec Tokens",
                "db_table": "zaptec_token",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="chargingsession",
            name="energy",
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name="Energy"),
        ),
        migrations.AlterUniqueTogether(
            name="energydetails",
            unique_together={("charging_session", "timestamp")},
        ),
    ]
