# Generated by Django 5.0 on 2024-01-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car_charging", "0003_zaptectoken_alter_chargingsession_energy_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpotPrices",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("no1", models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name="Price area 1")),
                ("no2", models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name="Price area 2")),
                ("no3", models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name="Price area 3")),
                ("no4", models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name="Price area 4")),
                ("no5", models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name="Price area 5")),
                ("start_time", models.DateTimeField(unique=True, verbose_name="Start time")),
                ("end_time", models.DateTimeField(verbose_name="End time")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
            ],
            options={
                "verbose_name": "Spot Prices",
                "verbose_name_plural": "Spot Prices",
                "db_table": "spot_prices",
                "ordering": ["start_time"],
            },
        ),
    ]
