# Generated by Django 5.0 on 2024-01-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car_charging", "0004_spotprices"),
    ]

    operations = [
        migrations.AddField(
            model_name="chargingsession",
            name="price_area",
            field=models.IntegerField(default=4, verbose_name="Price Area"),
        ),
    ]
