# Generated by Django 5.0 on 2024-02-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car_charging", "0006_energydetails_spot_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chargingsession",
            name="energy",
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name="Energy [kWh]"),
        ),
        migrations.AlterField(
            model_name="chargingsession",
            name="user_name",
            field=models.CharField(blank=True, default="", verbose_name="User Name"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="energydetails",
            name="energy",
            field=models.DecimalField(decimal_places=6, max_digits=8, verbose_name="Energy [kWh]"),
        ),
    ]
