# Generated by Django 5.0 on 2024-04-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car_charging", "0009_energydetails_cost"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpotPrice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nok_pr_kwh", models.DecimalField(decimal_places=7, max_digits=10, verbose_name="Price per kWh [NOK/kWh]")),
                ("eur_pr_kwh", models.DecimalField(decimal_places=7, max_digits=10, verbose_name="Price per kWh [EUR/kWh]")),
                ("exchange_rate", models.DecimalField(decimal_places=7, max_digits=10, verbose_name="Exchange rate")),
                ("start_time", models.DateTimeField(unique=True, verbose_name="Start time")),
                ("end_time", models.DateTimeField(null=True, verbose_name="End time")),
                ("price_area", models.IntegerField(verbose_name="Price area")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
            ],
            options={
                "verbose_name": "Spot Price",
                "verbose_name_plural": "Spot Prices",
                "db_table": "spot_price",
                "ordering": ["-start_time"],
            },
        ),
        migrations.AlterModelOptions(
            name="chargingsession",
            options={"ordering": ["-start_date_time"], "verbose_name": "Charging Session", "verbose_name_plural": "Charging Sessions"},
        ),
        migrations.AlterModelOptions(
            name="energydetails",
            options={"ordering": ["-timestamp"], "verbose_name": "Energy Detail", "verbose_name_plural": "Energy Details"},
        ),
        migrations.RemoveField(
            model_name="energydetails",
            name="cost",
        ),
        migrations.RemoveField(
            model_name="energydetails",
            name="spot_price",
        ),
    ]
