# Generated by Django 5.0.4 on 2024-05-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car_charging", "0011_delete_spotprices_alter_spotprice_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spotprice",
            name="start_time",
            field=models.DateTimeField(verbose_name="Start time"),
        ),
        migrations.AlterUniqueTogether(
            name="spotprice",
            unique_together={("start_time", "price_area")},
        ),
    ]
