# Generated by Django 5.0.4 on 2024-05-14 10:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car_charging", "0013_spotprice_spot_price_start_t_8abc5c_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GridPrice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day_fee", models.DecimalField(decimal_places=7, max_digits=10, verbose_name="Day fee per kWh [NOK/kWh]")),
                ("night_fee", models.DecimalField(decimal_places=7, max_digits=10, verbose_name="Night fee per kWh [NOK/kWh]")),
                (
                    "day_hour_from",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)],
                        verbose_name="Start hour for day fee",
                    ),
                ),
                (
                    "night_hour_from",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)],
                        verbose_name="Start hour for night fee",
                    ),
                ),
                ("start_date", models.DateField(unique=True, verbose_name="Start date")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
            ],
            options={
                "verbose_name": "Grid price",
                "verbose_name_plural": "Grid prices",
                "db_table": "grid_price",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="SpotPriceRefund",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deduction_threshold", models.DecimalField(decimal_places=7, max_digits=10, verbose_name="Deduction thershold [NOK/kWh]")),
                ("reduction_factor", models.DecimalField(decimal_places=7, max_digits=10, verbose_name="Reduction factor")),
                ("start_date", models.DateField(unique=True, verbose_name="Start date")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
            ],
            options={
                "verbose_name": "Spot price refund",
                "verbose_name_plural": "Spot price refunds",
                "db_table": "spot_price_refund",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="UsagePrice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nok_pr_kwh", models.DecimalField(decimal_places=7, max_digits=10, verbose_name="Price per kWh [NOK/kWh]")),
                ("start_date", models.DateField(unique=True, verbose_name="Start date")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
            ],
            options={
                "verbose_name": "Usage price",
                "verbose_name_plural": "Usage prices",
                "db_table": "usage_price",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="CostDetails",
            fields=[
                (
                    "energy_detail",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to="car_charging.energydetails"
                    ),
                ),
                ("session_id", models.IntegerField(editable=False, verbose_name="Charging session")),
                ("energy", models.DecimalField(decimal_places=6, editable=False, max_digits=8, verbose_name="Energy [kWh]")),
                ("timestamp", models.DateTimeField(editable=False, verbose_name="Timestamp")),
                ("price_area", models.IntegerField(editable=False, verbose_name="Price area")),
                ("spot_price_nok", models.DecimalField(decimal_places=7, editable=False, max_digits=10, verbose_name="Spot price per kWh [NOK/kWh]")),
                ("grid_price_nok", models.DecimalField(decimal_places=7, editable=False, max_digits=10, verbose_name="Grid price per kWh [NOK/kWh]")),
                (
                    "usage_price_nok",
                    models.DecimalField(decimal_places=7, editable=False, max_digits=10, verbose_name="Usage price per kWh [NOK/kWh]"),
                ),
                ("refund_price_nok", models.DecimalField(decimal_places=7, editable=False, max_digits=10, verbose_name="Refund per kWh [NOK/kWh]")),
                (
                    "fund_price_nok",
                    models.DecimalField(
                        decimal_places=7, default=0.01, editable=False, max_digits=10, verbose_name="Energy fund price per kWh [NOK/kWh]"
                    ),
                ),
                ("user_full_name", models.CharField(blank=True, editable=False, max_length=100, verbose_name="User Full Name")),
                ("user_id", models.UUIDField(blank=True, editable=False, null=True, verbose_name="User ID")),
                ("spot_cost", models.DecimalField(decimal_places=7, editable=False, max_digits=11, verbose_name="Spot cost [NOK]")),
                ("grid_cost", models.DecimalField(decimal_places=7, editable=False, max_digits=11, verbose_name="Grid cost [NOK]")),
                ("usage_cost", models.DecimalField(decimal_places=7, editable=False, max_digits=11, verbose_name="Usage cost [NOK]")),
                ("fund_cost", models.DecimalField(decimal_places=7, editable=False, max_digits=11, verbose_name="Fund cost [NOK]")),
                ("refund", models.DecimalField(decimal_places=7, editable=False, max_digits=11, verbose_name="Refund [NOK]")),
                ("total_cost", models.DecimalField(decimal_places=7, editable=False, max_digits=11, verbose_name="Total cost [NOK]")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("spot_price", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="car_charging.spotprice")),
                ("grid_price", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="car_charging.gridprice")),
                ("spot_price_refund", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="car_charging.spotpricerefund")),
                ("usage_price", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="car_charging.usageprice")),
            ],
            options={
                "verbose_name": "Cost detail",
                "verbose_name_plural": "Cost details",
                "db_table": "cost_details",
            },
        ),
    ]
