# Generated by Django 5.0.6 on 2025-01-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car_charging", "0014_gridprice_spotpricerefund_usageprice_costdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="energydetails",
            name="energy",
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name="Energy [kWh]"),
        ),
    ]
